spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:libra_bms;DB_CLOSE_DELAY=-1;MODE=MySQL;DATABASE_TO_LOWER=TRUE
    username: sa
    password: 
    druid:
      initial-size: 5
      max-active: 20
      min-idle: 5
      max-wait: 60000
  sql:
    init:
      schema-locations: classpath:db/h2-init.sql
      data-locations: classpath:db/h2-seed.sql
      mode: always
